// <auto-generated />
using System;
using DoctorAppointmentSystem.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoctorAppointmentSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<string>("ModeArtifact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlot")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "AppointmentDate", "TimeSlot")
                        .IsUnique();

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            ModeArtifact = "https://meet.hcl.com/room-john",
                            PatientId = 2,
                            Status = 0,
                            TimeSlot = 0,
                            TotalAmount = 500m
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 2,
                            ModeArtifact = "Apollo Clinic, Room 101",
                            PatientId = 3,
                            Status = 0,
                            TimeSlot = 1,
                            TotalAmount = 800m
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 3,
                            ModeArtifact = "https://meet.hcl.com/room-mike",
                            PatientId = 2,
                            Status = 1,
                            TimeSlot = 2,
                            TotalAmount = 600m
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 4,
                            ModeArtifact = "Apollo Clinic, Room 102",
                            PatientId = 3,
                            Status = 3,
                            TimeSlot = 3,
                            TotalAmount = 1000m
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DoctorId = 1,
                            ModeArtifact = "https://meet.hcl.com/room-john",
                            PatientId = 2,
                            Status = 2,
                            TimeSlot = 4,
                            TotalAmount = 500m
                        });
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpecialtyId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultationFee = 500m,
                            Mode = 0,
                            Name = "Dr. John Smith",
                            SpecialtyId = 6,
                            UserId = 4
                        },
                        new
                        {
                            Id = 2,
                            ConsultationFee = 800m,
                            Mode = 1,
                            Name = "Dr. Sarah Lee",
                            SpecialtyId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 3,
                            ConsultationFee = 600m,
                            Mode = 0,
                            Name = "Dr. Mike Tyson",
                            SpecialtyId = 7,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            ConsultationFee = 1000m,
                            Mode = 1,
                            Name = "Dr. Emily Davis",
                            SpecialtyId = 5,
                            UserId = 7
                        });
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.Specialty", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specialties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "General Physician"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pediatrics"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dermatology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gynecology"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Orthopedics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Cardiology"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Neurology"
                        });
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@hcl.com",
                            FullName = "System Admin",
                            PasswordHash = "$2a$12$TbRfUUFzgHdh0lFSWPu0CeWZ.GSj634SJrs8Ww1cnWcfNWwxhlDwe",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "rahul@test.com",
                            FullName = "Patient Rahul",
                            PasswordHash = "$2a$12$hGOeop7IbSbMcljWnNESIef.vOQUaOUqDmn0B9NZrd1JQPhna1QIW",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            Email = "priya@test.com",
                            FullName = "Patient Priya",
                            PasswordHash = "$2a$12$hGOeop7IbSbMcljWnNESIef.vOQUaOUqDmn0B9NZrd1JQPhna1QIW",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            Email = "john@hospital.com",
                            FullName = "Dr. John Smith",
                            PasswordHash = "$2a$12$ovyrpA80WJR5Kd9s8TpsQOUdZpD3aof9vEI..6pCkg1c7YKHPZAWG",
                            Role = 2
                        },
                        new
                        {
                            Id = 5,
                            Email = "sarah@hospital.com",
                            FullName = "Dr. Sarah Lee",
                            PasswordHash = "$2a$12$ovyrpA80WJR5Kd9s8TpsQOUdZpD3aof9vEI..6pCkg1c7YKHPZAWG",
                            Role = 2
                        },
                        new
                        {
                            Id = 6,
                            Email = "mike@hospital.com",
                            FullName = "Dr. Mike Tyson",
                            PasswordHash = "$2a$12$ovyrpA80WJR5Kd9s8TpsQOUdZpD3aof9vEI..6pCkg1c7YKHPZAWG",
                            Role = 2
                        },
                        new
                        {
                            Id = 7,
                            Email = "emily@hospital.com",
                            FullName = "Dr. Emily Davis",
                            PasswordHash = "$2a$12$ovyrpA80WJR5Kd9s8TpsQOUdZpD3aof9vEI..6pCkg1c7YKHPZAWG",
                            Role = 2
                        });
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.Appointment", b =>
                {
                    b.HasOne("DoctorAppointmentSystem.API.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentSystem.API.Entities.User", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.Doctor", b =>
                {
                    b.HasOne("DoctorAppointmentSystem.API.Entities.Specialty", "Specialty")
                        .WithMany("Doctors")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DoctorAppointmentSystem.API.Entities.User", "User")
                        .WithOne("DoctorProfile")
                        .HasForeignKey("DoctorAppointmentSystem.API.Entities.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialty");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.Specialty", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("DoctorAppointmentSystem.API.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
